#!/bin/bash

# check for required program
type virtualenv >/dev/null 2>&1 || { echo >&2 "You don't have virtualenv installed. Aborting."; exit 1; }

# check for required additional paramenter
if [ $# -lt 1 ]; then
   echo "You must specify the project name"
   exit 1;
fi

PWD=$(pwd)
PROJECT_NAME=$( basename "$1" )

mkdir -p "$1"

virtualenv "$1/venv"
. "$1/venv/bin/activate"
pip install django
cd $1
django-admin.py startproject $PROJECT_NAME
cd $PROJECT_NAME
./manage.py makemigrations
./manage.py migrate